# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Create local tool manifest
      run: dotnet new tool-manifest
    - name: Install dotnet-t4 global tool
      run: dotnet tool install --local dotnet-t4
    - name: Execute T4 templates
      shell: pwsh
      run: Get-ChildItem -Path "." -Filter "*.tt" -File -Recurse | ForEach-Object { dotnet t4 $_.FullName }
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
